#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

npx supabase start
npx supabase db reset --local --no-seed
npx supabase test db --local
npx supabase db lint --local --fail-on error

eval "$(npx supabase status -o env)"
local_key="${PUBLISHABLE_KEY:-${ANON_KEY:-}}"

if [[ -z "${API_URL:-}" || -z "$local_key" ]]; then
  echo "Local Supabase did not return the required frontend values." >&2
  exit 1
fi

case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *)
    echo "Refusing to configure a non-local Supabase URL." >&2
    exit 1
    ;;
esac

env_file="$repo_root/.env.local"
marker="# Generated by .devcontainer/start-local-supabase.sh"
if [[ -f "$env_file" ]] && ! grep -Fqx "$marker" "$env_file"; then
  echo "Refusing to overwrite an existing .env.local not owned by the cloud setup." >&2
  exit 1
fi

umask 077
temp_file="$(mktemp "$repo_root/.env.local.XXXXXX")"
trap 'rm -f "$temp_file"' EXIT
{
  echo "$marker"
  printf 'VITE_SUPABASE_URL=%s\n' "$API_URL"
  printf 'VITE_SUPABASE_PUBLISHABLE_KEY=%s\n' "$local_key"
} > "$temp_file"
mv "$temp_file" "$env_file"
trap - EXIT

echo "Local Supabase is ready and .env.local contains local-only frontend settings."
